# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: usage-config
data:
  SERVER_PORT: "8080"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "telecomdb"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"

  # Checkpoint Store 설정 추가 
  BLOB_CONTAINER: "unicorn-checkpoints-usageq"
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: usage-secret
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Passw0rd"
  REDIS_PASSWORD: "Passw0rd"
  # EventHub 관련 설정 추가
  EVENT_HUB_NAME: "unicorn-name-usageq"
  EVENT_HUB_CONNECTION_STRING: "Endpoint=sb://unicorn-ns-usageq.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BH2c1qnm0H9N3rIN8tqPgCWpihk6FGDg7+AEhPlsyhw="
  STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=unicornstorageusageq;AccountKey=6Q9RQ2mFy7IkOz8v4NDuCpPz8C+S8KSTTEJjCTANpOGZPZp2w145S7WR3i73ZN26V7vNdvn0rubk+ASt1Kfoig==;BlobEndpoint=https://unicornstorageusageq.blob.core.windows.net/;FileEndpoint=https://unicornstorageusageq.file.core.windows.net/;QueueEndpoint=https://unicornstorageusageq.queue.core.windows.net/;TableEndpoint=https://unicornstorageusageq.table.core.windows.net/"

---
# Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-management-service
  template:
    metadata:
      labels:
        app: usage-management-service
    spec:
      containers:
      - name: usage-management-service
        image: unicorncr.azurecr.io/telecom/usage-management-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: usage-config
        - secretRef:
            name: usage-secret
---
apiVersion: v1
kind: Service
metadata:
  name: usage-management-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: usage-management-service
---
# Query Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-query-service
  template:
    metadata:
      labels:
        app: usage-query-service
    spec:
      containers:
      - name: usage-query-service
        image: unicorncr.azurecr.io/telecom/usage-query-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: usage-config
        - secretRef:
            name: usage-secret
        env:
        - name: POSTGRES_HOST
          value: postgres-usageq-postgresql-read-hl
        - name: REDIS_HOST
          value: redis-usageq-master
---
apiVersion: v1
kind: Service
metadata:
  name: usage-query-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: usage-query-service
---
# Update Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-update-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage-update-service
  template:
    metadata:
      labels:
        app: usage-update-service
    spec:
      containers:
      - name: usage-update-service
        image: unicorncr.azurecr.io/telecom/usage-update-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: usage-config
        - secretRef:
            name: usage-secret
        env:
        - name: POSTGRES_HOST
          value: postgres-usageq-postgresql-primary-hl
        - name: REDIS_HOST
          value: redis-usageq-master
---
apiVersion: v1
kind: Service
metadata:
  name: usage-update-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: usage-update-service
