name: Usage Query System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: unicorncr.azurecr.io
  RESOURCE_GROUP: tiu-dgga-rg
  CLUSTER_NAME: unicorn-aks
  NAMESPACE: unicorn-usageq-ns

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew usage-management-service:clean usage-management-service:build -x test
          ./gradlew usage-query-service:clean usage-query-service:build -x test
          ./gradlew usage-update-service:clean usage-update-service:build -x test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-builds
          path: |
            usage-management-service/build/libs/
            usage-query-service/build/libs/
            usage-update-service/build/libs/

  release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.create-tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Generate image tag
        id: create-tag
        run: |
          echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-builds

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          # Management Service
          docker build -f deployment/Dockerfile-usage-management-service \
            -t ${{ env.REGISTRY }}/telecom/usage-management-service:${{ steps.create-tag.outputs.tag }} \
            -t ${{ env.REGISTRY }}/telecom/usage-management-service:latest .
          docker push ${{ env.REGISTRY }}/telecom/usage-management-service:${{ steps.create-tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/telecom/usage-management-service:latest
          
          # Query Service
          docker build -f deployment/Dockerfile-usage-query-service \
            -t ${{ env.REGISTRY }}/telecom/usage-query-service:${{ steps.create-tag.outputs.tag }} \
            -t ${{ env.REGISTRY }}/telecom/usage-query-service:latest .
          docker push ${{ env.REGISTRY }}/telecom/usage-query-service:${{ steps.create-tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/telecom/usage-query-service:latest
          
          # Update Service
          docker build -f deployment/Dockerfile-usage-update-service \
            -t ${{ env.REGISTRY }}/telecom/usage-update-service:${{ steps.create-tag.outputs.tag }} \
            -t ${{ env.REGISTRY }}/telecom/usage-update-service:latest .
          docker push ${{ env.REGISTRY }}/telecom/usage-update-service:${{ steps.create-tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/telecom/usage-update-service:latest

  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Create namespace if not exists
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Generate Deployment Manifest
        run: |
          # Export variables for envsubst
          export namespace=${{ env.NAMESPACE }}
          export management_image_path=${{ env.REGISTRY }}/telecom/usage-management-service:${{ needs.release.outputs.imageTag }}
          export query_image_path=${{ env.REGISTRY }}/telecom/usage-query-service:${{ needs.release.outputs.imageTag }}
          export update_image_path=${{ env.REGISTRY }}/telecom/usage-update-service:${{ needs.release.outputs.imageTag }}
          export resources_requests_cpu=250m
          export resources_requests_memory=512Mi
          export resources_limits_cpu=500m
          export resources_limits_memory=1024Mi
          export EVENT_HUB_CONNECTION_STRING="${{ secrets.EVENT_HUB_CONNECTION_STRING }}"
          export EVENT_HUB_NAME="${{ secrets.EVENT_HUB_NAME }}"
          export STORAGE_CONNECTION_STRING="${{ secrets.STORAGE_CONNECTION_STRING }}"
          
          # Generate deployment file
          envsubst < deployment/deploy.yaml.template > deployment/deploy.yaml
          
          # Debug: Print generated manifest
          echo "Generated manifest:"
          cat deployment/deploy.yaml

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment/deploy.yaml
          
          # Wait for pods to be ready
          kubectl wait --for=condition=ready pod -l "app=usage-management-service" -n ${{ env.NAMESPACE }} --timeout=300s
          kubectl wait --for=condition=ready pod -l "app=usage-query-service" -n ${{ env.NAMESPACE }} --timeout=300s
          kubectl wait --for=condition=ready pod -l "app=usage-update-service" -n ${{ env.NAMESPACE }} --timeout=300s

      - name: Verify Deployment
        run: |
          echo "Verifying service endpoints..."
          
          # Get service IPs
          MANAGEMENT_IP=$(kubectl get svc usage-management-service -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          QUERY_IP=$(kubectl get svc usage-query-service -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          UPDATE_IP=$(kubectl get svc usage-update-service -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          
          echo "Management Service IP: $MANAGEMENT_IP"
          echo "Query Service IP: $QUERY_IP" 
          echo "Update Service IP: $UPDATE_IP"
          
          if [ -z "$MANAGEMENT_IP" ] || [ -z "$QUERY_IP" ] || [ -z "$UPDATE_IP" ]; then
            echo "Error: Service IPs not available"
            exit 1
          fi