name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: unicorncr.azurecr.io
  NAMESPACE: unicorn-usageq-ns
  RESOURCE_GROUP: tiu-dgga-rg
  CLUSTER_NAME: unicorn-aks
  IMAGE_ORG: telecom

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew usage-management-service:clean usage-management-service:build -x test
          ./gradlew usage-query-service:clean usage-query-service:build -x test
          ./gradlew usage-update-service:clean usage-update-service:build -x test

  release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.create_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Create Image Tag
        id: create_tag
        run: |
          tag=$(date +'%Y%m%d%H%M%S')
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name unicorncr

      - name: Build and Push Management Service
        run: |
          docker build -f deployment/Dockerfile-usage-management-service \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-management-service:${{ steps.create_tag.outputs.tag }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-management-service:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-management-service:${{ steps.create_tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-management-service:latest

      - name: Build and Push Query Service
        run: |
          docker build -f deployment/Dockerfile-usage-query-service \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-query-service:${{ steps.create_tag.outputs.tag }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-query-service:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-query-service:${{ steps.create_tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-query-service:latest

      - name: Build and Push Update Service
        run: |
          docker build -f deployment/Dockerfile-usage-update-service \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-update-service:${{ steps.create_tag.outputs.tag }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-update-service:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-update-service:${{ steps.create_tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-update-service:latest

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Create namespace
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Generate deployment manifest
        run: |
          # Export variables for envsubst
          export namespace=${{ env.NAMESPACE }}
          export management_image_path=${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-management-service:${{ needs.release.outputs.imageTag }}
          export query_image_path=${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-query-service:${{ needs.release.outputs.imageTag }}
          export update_image_path=${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/usage-update-service:${{ needs.release.outputs.imageTag }}
          export resources_requests_cpu=250m
          export resources_requests_memory=512Mi
          export resources_limits_cpu=500m
          export resources_limits_memory=1024Mi
          
          # Generate deployment file
          envsubst < deployment/deploy.yaml.template > deployment/deploy.yaml
          
          # Print generated manifest for debugging
          echo "Generated manifest:"
          cat deployment/deploy.yaml

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment/deploy.yaml

      - name: Verify deployment
        run: |
          echo "Waiting for services to be ready..."
          kubectl wait --for=condition=ready pod -l "app=usage-management-service" -n ${{ env.NAMESPACE }} --timeout=300s
          kubectl wait --for=condition=ready pod -l "app=usage-query-service" -n ${{ env.NAMESPACE }} --timeout=300s
          kubectl wait --for=condition=ready pod -l "app=usage-update-service" -n ${{ env.NAMESPACE }} --timeout=300s
          
          echo "Verifying service endpoints..."
          MGMT_IP=$(kubectl get svc usage-management-service -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          QUERY_IP=$(kubectl get svc usage-query-service -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          UPDATE_IP=$(kubectl get svc usage-update-service -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          
          echo "Management Service IP: $MGMT_IP"
          echo "Query Service IP: $QUERY_IP" 
          echo "Update Service IP: $UPDATE_IP"
          
          if [ -z "$MGMT_IP" ] || [ -z "$QUERY_IP" ] || [ -z "$UPDATE_IP" ]; then
            echo "Error: Service IPs not available"
            exit 1
          fi
